[package]
name = "csv_view"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
atty = "0.2.14"
clap = { version = "4.5.23", features = ["derive"] }
comfy-table = "7.1.3"
csv = "1.3.1"
flate2 = "1.0.35"
log = "0.4.22"
thiserror = "1.0.60"
